### ISSUE TITLE
Status API reports "normal" for both "msa" and "mojang" accounts

### ISSUE THREAD

**Issue by BerndSchmecka** [88/gapple-docs#1]
Hello,

Yesterday, the Status API stopped working for some time (It displayed `{"error":"There was an issue communicating with Mojang or the provided name was invalid. Try again later!"}`). After it went back on, it has different outputs: While e.g. `Tremendous` is still shown as `legacy`, both Microsoft and Mojang accounts are now both shown as `normal`, making them indistinguishable.

Kind regards

**Comment by withdrew** [comment]
This is because mojang messed up there api it should all be fixed now.

**Comment by withdrew** [comment]
https://api.gapple.pw/status/kent600

**Comment by BerndSchmecka** [comment]
Alright, thank you :D
